//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineOrc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineOrc.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error while executing action &apos;{ActionName}&apos;.
        /// </summary>
        internal static string ActionExecuteError {
            get {
                return ResourceManager.GetString("ActionExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file does not exist.
        /// </summary>
        internal static string ArgumentFileNotExist {
            get {
                return ResourceManager.GetString("ArgumentFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading asset index.
        /// </summary>
        internal static string AssetRestoreDownloadIndex {
            get {
                return ResourceManager.GetString("AssetRestoreDownloadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to read index &apos;{0}&apos;.
        /// </summary>
        internal static string AssetRestoreIndexReadFailed {
            get {
                return ResourceManager.GetString("AssetRestoreIndexReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing or invalid asset index &apos;{0}&apos;.
        /// </summary>
        internal static string AssetRestoreMissingIndex {
            get {
                return ResourceManager.GetString("AssetRestoreMissingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login failed.
        /// </summary>
        internal static string CommandGenericLoginFailed {
            get {
                return ResourceManager.GetString("CommandGenericLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such profile: &quot;{0}&quot;.
        /// </summary>
        internal static string CommandGenericNoProfile {
            get {
                return ResourceManager.GetString("CommandGenericNoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches a profile.
        /// </summary>
        internal static string CommandLaunch {
            get {
                return ResourceManager.GetString("CommandLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile to launch.
        /// </summary>
        internal static string CommandLaunchArgumentName {
            get {
                return ResourceManager.GetString("CommandLaunchArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default account is unset or invalid.
        /// </summary>
        internal static string CommandLaunchFailNoDefaultAccount {
            get {
                return ResourceManager.GetString("CommandLaunchFailNoDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t find a default Java to use; try specify or register one.
        /// </summary>
        internal static string CommandLaunchFailNoJava {
            get {
                return ResourceManager.GetString("CommandLaunchFailNoJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile &quot;{0}&quot; has a non-existent version; try restore it first.
        /// </summary>
        internal static string CommandLaunchFailNoVersion {
            get {
                return ResourceManager.GetString("CommandLaunchFailNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot create process.
        /// </summary>
        internal static string CommandLaunchFailProcessStart {
            get {
                return ResourceManager.GetString("CommandLaunchFailProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch in Demo Mode.
        /// </summary>
        internal static string CommandLaunchOptionDemo {
            get {
                return ResourceManager.GetString("CommandLaunchOptionDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Java executable to use.
        /// </summary>
        internal static string CommandLaunchOptionJavaFile {
            get {
                return ResourceManager.GetString("CommandLaunchOptionJavaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registered name of Java to use.
        /// </summary>
        internal static string CommandLaunchOptionJavaName {
            get {
                return ResourceManager.GetString("CommandLaunchOptionJavaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of memory Minecraft can use.
        /// </summary>
        internal static string CommandLaunchOptionMaxMemory {
            get {
                return ResourceManager.GetString("CommandLaunchOptionMaxMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum amount of memory Minecraft is assigned.
        /// </summary>
        internal static string CommandLaunchOptionMinMemory {
            get {
                return ResourceManager.GetString("CommandLaunchOptionMinMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restore the profile.
        /// </summary>
        internal static string CommandLaunchOptionNoRestore {
            get {
                return ResourceManager.GetString("CommandLaunchOptionNoRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new profile.
        /// </summary>
        internal static string CommandNew {
            get {
                return ResourceManager.GetString("CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new profile.
        /// </summary>
        internal static string CommandNewArgumentName {
            get {
                return ResourceManager.GetString("CommandNewArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the new profile.
        /// </summary>
        internal static string CommandNewArgumentVersion {
            get {
                return ResourceManager.GetString("CommandNewArgumentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile &apos;{0}&apos; already exists.
        /// </summary>
        internal static string CommandNewFailAlreadyExists {
            get {
                return ResourceManager.GetString("CommandNewFailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile name &apos;{0}&apos; does not conform to pattern &apos;{1}&apos;.
        /// </summary>
        internal static string CommandNewFailNameInvalid {
            get {
                return ResourceManager.GetString("CommandNewFailNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version &apos;{0}&apos; does not exist and version install is disabled.
        /// </summary>
        internal static string CommandNewFailNoInstallVersion {
            get {
                return ResourceManager.GetString("CommandNewFailNoInstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not install the specified version if not already installed.
        /// </summary>
        internal static string CommandNewOptionNoInstallVersion {
            get {
                return ResourceManager.GetString("CommandNewOptionNoInstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object state is invalid because &apos;{0}&apos; is null..
        /// </summary>
        internal static string ExceptionStateNull {
            get {
                return ResourceManager.GetString("ExceptionStateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error when creating required directories.
        /// </summary>
        internal static string InitializationDirectoryError {
            get {
                return ResourceManager.GetString("InitializationDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error reading Java runtime list.
        /// </summary>
        internal static string InitializationLoadRuntimesError {
            get {
                return ResourceManager.GetString("InitializationLoadRuntimesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot get client manifest: error {0}.
        /// </summary>
        internal static string InstallManifestFailCannotGetJson {
            get {
                return ResourceManager.GetString("InstallManifestFailCannotGetJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot save client manifest.
        /// </summary>
        internal static string InstallManifestFailCannotSaveJson {
            get {
                return ResourceManager.GetString("InstallManifestFailCannotSaveJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such version &apos;{Version}&apos;.
        /// </summary>
        internal static string InstallManifestFailNoSuchVersion {
            get {
                return ResourceManager.GetString("InstallManifestFailNoSuchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List and manage Java runtimes.
        /// </summary>
        internal static string JavaBranch {
            get {
                return ResourceManager.GetString("JavaBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or set the default Java runtime.
        /// </summary>
        internal static string JavaDefaultCommand {
            get {
                return ResourceManager.GetString("JavaDefaultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default Java runtime is set.
        /// </summary>
        internal static string JavaDefaultFailNoDefault {
            get {
                return ResourceManager.GetString("JavaDefaultFailNoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Java runtime to set as default.
        /// </summary>
        internal static string JavaDefaultValueArgument {
            get {
                return ResourceManager.GetString("JavaDefaultValueArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such Java runtime &apos;{0}&apos;.
        /// </summary>
        internal static string JavaFailNoSuchRuntime {
            get {
                return ResourceManager.GetString("JavaFailNoSuchRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to save runtime config.
        /// </summary>
        internal static string JavaFailSave {
            get {
                return ResourceManager.GetString("JavaFailSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List registered Java runtimes.
        /// </summary>
        internal static string JavaListCommand {
            get {
                return ResourceManager.GetString("JavaListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a Java runtime.
        /// </summary>
        internal static string JavaRegisterCommand {
            get {
                return ResourceManager.GetString("JavaRegisterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runtime with name &apos;{0}&apos; already exists.
        /// </summary>
        internal static string JavaRegisterFailExistingName {
            get {
                return ResourceManager.GetString("JavaRegisterFailExistingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Java runtime.
        /// </summary>
        internal static string JavaRegisterNameArgument {
            get {
                return ResourceManager.GetString("JavaRegisterNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Java executable.
        /// </summary>
        internal static string JavaRegisterPathArgument {
            get {
                return ResourceManager.GetString("JavaRegisterPathArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Java register.
        /// </summary>
        internal static string JavaRegisterVersionArgument {
            get {
                return ResourceManager.GetString("JavaRegisterVersionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string JavaRegisterVersionColumn {
            get {
                return ResourceManager.GetString("JavaRegisterVersionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto added.
        /// </summary>
        internal static string JavaRegistryAutoAddedColumn {
            get {
                return ResourceManager.GetString("JavaRegistryAutoAddedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JavaRegistryNameColumn {
            get {
                return ResourceManager.GetString("JavaRegistryNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string JavaRegistryPathColumn {
            get {
                return ResourceManager.GetString("JavaRegistryPathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints output in a machine-readable format.
        /// </summary>
        internal static string MachineOption {
            get {
                return ResourceManager.GetString("MachineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to download.
        /// </summary>
        internal static string OperationDownloadFail {
            get {
                return ResourceManager.GetString("OperationDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to download: error {0}.
        /// </summary>
        internal static string OperationDownloadFailHttp {
            get {
                return ResourceManager.GetString("OperationDownloadFailHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occurred.
        /// </summary>
        internal static string OperationGenericExceptionError {
            get {
                return ResourceManager.GetString("OperationGenericExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot create directory &apos;{0}&apos;.
        /// </summary>
        internal static string OperationGenericMakeDirFail {
            get {
                return ResourceManager.GetString("OperationGenericMakeDirFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string OperationGenericProgressText {
            get {
                return ResourceManager.GetString("OperationGenericProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to verify hash.
        /// </summary>
        internal static string OperationHashFail {
            get {
                return ResourceManager.GetString("OperationHashFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to read client manifest.
        /// </summary>
        internal static string OperationReadClientManifestFailed {
            get {
                return ResourceManager.GetString("OperationReadClientManifestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile name &apos;{0}&apos; violates the profile name rule: {1}.
        /// </summary>
        internal static string ProfileFailRuleViolation {
            get {
                return ResourceManager.GetString("ProfileFailRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error when reading read profile &apos;{0}&apos;.
        /// </summary>
        internal static string ProfileReadError {
            get {
                return ResourceManager.GetString("ProfileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile &apos;{0}&apos; data contains only null.
        /// </summary>
        internal static string ProfileReadFailNull {
            get {
                return ResourceManager.GetString("ProfileReadFailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore client jar.
        /// </summary>
        internal static string RestoreClientJarAction {
            get {
                return ResourceManager.GetString("RestoreClientJarAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing client artefact in client manifest.
        /// </summary>
        internal static string RestoreClientJarFailNoArtefact {
            get {
                return ResourceManager.GetString("RestoreClientJarFailNoArtefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to restore client jar because client json is missing.
        /// </summary>
        internal static string RestoreClientJarFailNoManifest {
            get {
                return ResourceManager.GetString("RestoreClientJarFailNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored library &apos;{0}&apos;.
        /// </summary>
        internal static string RestoreLibraryDownloaded {
            get {
                return ResourceManager.GetString("RestoreLibraryDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minecraft Instance Orchestrator.
        /// </summary>
        internal static string RootDescription {
            get {
                return ResourceManager.GetString("RootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or download Minecraft client versions.
        /// </summary>
        internal static string VersionBranch {
            get {
                return ResourceManager.GetString("VersionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install or restore a client version.
        /// </summary>
        internal static string VersionInstallCommand {
            get {
                return ResourceManager.GetString("VersionInstallCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the specified version already exists.
        /// </summary>
        internal static string VersionInstallCommandFailExists {
            get {
                return ResourceManager.GetString("VersionInstallCommandFailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the version to install.
        /// </summary>
        internal static string VersionInstallIdArgument {
            get {
                return ResourceManager.GetString("VersionInstallIdArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restore client jar.
        /// </summary>
        internal static string VersionInstallNoRestoreOption {
            get {
                return ResourceManager.GetString("VersionInstallNoRestoreOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the assets and libraries of a version.
        /// </summary>
        internal static string VersionRestoreCommand {
            get {
                return ResourceManager.GetString("VersionRestoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version &apos;{0}&apos; does not exist, install it first.
        /// </summary>
        internal static string VersionRestoreFailNoVersion {
            get {
                return ResourceManager.GetString("VersionRestoreFailNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version to restore.
        /// </summary>
        internal static string VersionRestoreVersionArgument {
            get {
                return ResourceManager.GetString("VersionRestoreVersionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes pre-Classic, Classic, Infdev and Alpha versions.
        /// </summary>
        internal static string VersionSearchAlphaOption {
            get {
                return ResourceManager.GetString("VersionSearchAlphaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Beta phase versions.
        /// </summary>
        internal static string VersionSearchBetaOption {
            get {
                return ResourceManager.GetString("VersionSearchBetaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Minecraft versions.
        /// </summary>
        internal static string VersionSearchCommand {
            get {
                return ResourceManager.GetString("VersionSearchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treats the search term as Regex.
        /// </summary>
        internal static string VersionSearchRegexOption {
            get {
                return ResourceManager.GetString("VersionSearchRegexOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes development versions.
        /// </summary>
        internal static string VersionSearchSnapshotOption {
            get {
                return ResourceManager.GetString("VersionSearchSnapshotOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term to search version names with.
        /// </summary>
        internal static string VersionSearchTermArgument {
            get {
                return ResourceManager.GetString("VersionSearchTermArgument", resourceCulture);
            }
        }
    }
}
