//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineOrc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineOrc.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error while executing action &apos;{ActionName}&apos;.
        /// </summary>
        internal static string ActionExecuteError {
            get {
                return ResourceManager.GetString("ActionExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot get client manifest: error {0}.
        /// </summary>
        internal static string InstallManifestFailCannotGetJson {
            get {
                return ResourceManager.GetString("InstallManifestFailCannotGetJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot save client manifest.
        /// </summary>
        internal static string InstallManifestFailCannotSaveJson {
            get {
                return ResourceManager.GetString("InstallManifestFailCannotSaveJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such version &apos;{Version}&apos;.
        /// </summary>
        internal static string InstallManifestFailNoSuchVersion {
            get {
                return ResourceManager.GetString("InstallManifestFailNoSuchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints output in a machine-readable format.
        /// </summary>
        internal static string MachineOption {
            get {
                return ResourceManager.GetString("MachineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to download.
        /// </summary>
        internal static string OperationDownloadFail {
            get {
                return ResourceManager.GetString("OperationDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to download: error {0}.
        /// </summary>
        internal static string OperationDownloadFailHttp {
            get {
                return ResourceManager.GetString("OperationDownloadFailHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore client jar.
        /// </summary>
        internal static string RestoreClientJarAction {
            get {
                return ResourceManager.GetString("RestoreClientJarAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing client artefact in client manifest.
        /// </summary>
        internal static string RestoreClientJarFailNoArtefact {
            get {
                return ResourceManager.GetString("RestoreClientJarFailNoArtefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to restore client jar because client json is missing.
        /// </summary>
        internal static string RestoreClientJarFailNoManifest {
            get {
                return ResourceManager.GetString("RestoreClientJarFailNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored library &apos;{0}&apos;.
        /// </summary>
        internal static string RestoreLibraryDownloaded {
            get {
                return ResourceManager.GetString("RestoreLibraryDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Minecraft Instance Orchestrator.
        /// </summary>
        internal static string RootDescription {
            get {
                return ResourceManager.GetString("RootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or download Minecraft client versions.
        /// </summary>
        internal static string VersionBranch {
            get {
                return ResourceManager.GetString("VersionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install or restore a client version.
        /// </summary>
        internal static string VersionInstallCommand {
            get {
                return ResourceManager.GetString("VersionInstallCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the specified version already exists.
        /// </summary>
        internal static string VersionInstallCommandFailExists {
            get {
                return ResourceManager.GetString("VersionInstallCommandFailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the version to install.
        /// </summary>
        internal static string VersionInstallIdArgument {
            get {
                return ResourceManager.GetString("VersionInstallIdArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restore client jar.
        /// </summary>
        internal static string VersionInstallNoRestoreOption {
            get {
                return ResourceManager.GetString("VersionInstallNoRestoreOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes pre-Classic, Classic, Infdev and Alpha versions.
        /// </summary>
        internal static string VersionSearchAlphaOption {
            get {
                return ResourceManager.GetString("VersionSearchAlphaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Beta phase versions.
        /// </summary>
        internal static string VersionSearchBetaOption {
            get {
                return ResourceManager.GetString("VersionSearchBetaOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Minecraft versions.
        /// </summary>
        internal static string VersionSearchCommand {
            get {
                return ResourceManager.GetString("VersionSearchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treats the search term as Regex.
        /// </summary>
        internal static string VersionSearchRegexOption {
            get {
                return ResourceManager.GetString("VersionSearchRegexOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes development versions.
        /// </summary>
        internal static string VersionSearchSnapshotOption {
            get {
                return ResourceManager.GetString("VersionSearchSnapshotOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term to search version names with.
        /// </summary>
        internal static string VersionSearchTermArgument {
            get {
                return ResourceManager.GetString("VersionSearchTermArgument", resourceCulture);
            }
        }
    }
}
