on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        environment: "Workflows Default"
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.1
            - name: Setup .NET
              uses: actions/setup-dotnet@v5.0.1
              with:
                  dotnet-version: 10.x
            - name: Cake build
              env:
                  MINEORC_BUILD_ENTRA_APP_ID: ${{ secrets.MINEORC_BUILD_ENTRA_APP_ID }}
                  MINEORC_BUILD_ENTRA_TENANT_ID: ${{ secrets.MINEORC_BUILD_ENTRA_TENANT_ID }}
              run: "${{ github.workspace }}/build.sh"
            - name: Upload artefact
              uses: actions/upload-artifact@v6
              with:
                  name: 'App binaries'
                  path: '${{ github.workspace }}/MineOrc/bin'